FROM busybox:latest
LABEL "author" = "Ajay Kumar Baljoshi"
LABEL "version" = 1.0
LABEL "description" = This is a docker \
                      has multiple labels
                      
CMD echo "Docker image with multiple labels"