FROM centos:7
WORKDIR /tmp
RUN yum install -y unzip
ADD https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip .
RUN unzip terraform_0.12.28_linux_amd64.zip && cp terraform /usr/local/bin/terraform
CMD terraform --version
